In [1]:
#from SynthNN.utils import synthNN_predict
import numpy as np
from SynthNN.utils import get_features, synthNN_predict
import tensorflow as tf
import os

# Generate Synthesizability Predictions Using a Pre-trained SynthNN Model

In [2]:
#Option 1: Provide list of formulas directly
#Expected output:
#array([0.00387382, 0.6501727 ]

data=['Na3O','KCl']
output_file_name='output_formula_preds.txt'
saved_model_dir='./Trained_models/Paper_final_model/'

synthNN_predict(data,output_file_name, saved_model_dir)

Instructions for updating:
Use `tf.global_variables_initializer` instead.


array([0.00387382, 0.6501727 ], dtype=float32)

In [3]:
#Option 2: Read in formulas from text file
data=np.loadtxt('input_formulas.txt',dtype=str)
output_file_name='output_formula_preds.txt'
saved_model_dir='./Trained_models/Paper_final_model/'

synthNN_predict(data,output_file_name, saved_model_dir)

array([0.00387382, 0.6501727 ], dtype=float32)